### ISSUE TITLE
Core issue evaluation process

### ISSUE THREAD

**Issue by platinumazure** [mysticatea/eslint-evaluating-issues#1]
This has been a really awesome utility for tracking issues that might be worth going after. Thanks @mysticatea for developing this!

Currently, all issues in "evaluating" state show up here, and this utility assumes the "champion and 3 :+1:s" evaluation rules for all issues. However, this only really applies to rule issues. Core issues need TSC discussion. So while it's useful to have core issues on this page in order to show community popularity, I wonder if they should be categorized differently.

What I would suggest is that core issues should get their own table (i.e., filter out label:core from the current tables, then add a new table with label:core issues). And in that table, we can show how many upvotes it has from the community, as well as supporters and opponents from the team, but not try to classify it as "needs one more supporter" etc. because the only thing that matters is if the issue has been reviewed by the TSC.

Example issue: eslint/eslint#10855

**Comment by platinumazure** [comment]
Another thought: Maybe we should only label issues as "evaluating" if they're following this process? (In other words, core issues wouldn't use the "evaluating" label.)

**Comment by mysticatea** [comment]
Thank you for this issue.

Sorry, I had been away from OSS because of health problems.
I will update this tool to separate the issues which have `core`/`cli` labels.

**Comment by platinumazure** [comment]
@mysticatea No worries-- your health comes first, hope you get better!

Thanks for making the changes!
