### ISSUE TITLE
Are PRs included here?

### ISSUE THREAD

**Issue by platinumazure** [mysticatea/eslint-evaluating-issues#3]
Since we allow PRs to go through the evaluation process (at least, for non-core issues), it seems reasonable to pull at least some issues in. Not 100% sure which way we want to go here, though.

**Comment by mysticatea** [comment]
I'm working on this.

**Comment by mysticatea** [comment]
I made the following behavior:

- PRs which don't have "`fixes #xxx`" are handled as same as issues.
- PRs which have "`fixes #xxx`" are skipped and linked from the title of the issue.
    - If the linked issue has been closed, the PRs are listed in [Pull requests for closed issue](https://github.com/mysticatea/eslint-evaluating-issues#pull-requests-for-closed-issue) section.

Thank you.
